version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async_api
    ports:
      - "8000:8000"
    env_file:
      - .env
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - ELASTIC_HOST=elasticsearch
#      - ELASTIC_PORT=9200
#      - ELASTIC_SCHEMA=http://
    depends_on:
      - redis
      - elasticsearch
    restart: unless-stopped
    networks:
      - api_network_external
      - api_network_internal

  postgres_to_el:
    container_name: postgres_to_el
    build: ./postgres_to_el
    env_file: ./.env
    depends_on:
      - elasticsearch
      - dba
    networks:
      - api_network_internal

  dba:
    container_name: dba
    image: postgres:16
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data97/
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    env_file: ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d database" ]

      #      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      - api_network_internal

  redis:
    image: redis:7-alpine
    container_name: async_api_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - api_network_internal

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: async_api_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - api_network_internal

volumes:
  es_data:
    name: es_volume
    driver: local
  redis_data:
    name: redis_volume
  postgres_data:
    name: postgres_volume
    driver: local

networks:
  api_network_external:
    driver: bridge
    name: api_network_external
  api_network_internal:
    driver: bridge
    name: api_network_internal