version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - api_network_external
      - api_network_internal

  postgres_to_el:
    container_name: postgres_to_el
    build: ./postgres_to_el
    env_file: ./.env
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - api_network_internal

  postgres_to_el_genres:
    container_name: postgres_to_el_genres
    build: ./postgres_to_el_genres
    env_file: ./.env
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - api_network_internal

  db:
    container_name: db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data96/
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    env_file: ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U igor -d database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      - api_network_internal

  redis:
    image: redis:7-alpine
    container_name: async_api_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - api_network_internal

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: async_api_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health > /dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - api_network_internal

volumes:
  es_data:
    name: es_volume
    driver: local
  redis_data:
    name: redis_volume
  postgres_data:
    name: postgres_volume
    driver: local

networks:
  api_network_external:
    driver: bridge
    name: api_network_external
  api_network_internal:
    driver: bridge
    name: api_network_internal